### ISSUE TITLE
При некоректных данных в фильтре (несуществующее значение енама, строка вместо числа...) должна быть ошибка

### ISSUE THREAD

**Issue by AlphaBeth** [daniilprohorov/soaLab1#3]

**Comment by daniilprohorov** [comment]
Front: https://github.com/daniilprohorov/soaFront/commit/c2bd29a2ce614d58b15ad73a8de1039e57b3ae84
Backend: https://github.com/daniilprohorov/soaLab1/commit/96baf602a8af2269b7d86ffa42b33bfe92e8f583
